### ISSUE TITLE
Auth tables not escaped by default on PostgreSQL

### ISSUE THREAD

**Issue by tjtimer** [gi0baro/weppy#86] opened 2016-01-27 11:55 UTC
Hi,
just started with weppy (0.6 with python 3.5 in virtualenv).
When I copy the complete "bloggy.py"-example and start with 'weppy --app bloggy.py setup' 
I get "Error: no command 'setup'".

**Comment by gi0baro** [comment] 2016-01-27 13:17
Hi @tjtimer,
just checked with python 3.5 and I don't get any errors. Are you running the command inside the *bloggy* folder? What's the output of `weppy -a bloggy.py --help` ?

**Comment by tjtimer** [comment] 2016-01-29 13:20
Hey my output looks like this:
$ weppy -a bloggy.py --help      
Usage: weppy [OPTIONS] COMMAND [ARGS]...

Options:
  -a, --app TEXT  The application to run
  --help          Show this message and exit.

Commands:
  migrations  Runs migration operations.
  run         Runs a development server.
  shell       Runs a shell in the app context.

**Comment by tjtimer** [comment] 2016-01-29 13:31
Hey my output from "weppy -a bloggy.py --help" looks like this:

Usage: weppy [OPTIONS] COMMAND [ARGS]...

Options:
-a, --app TEXT The application to run
--help Show this message and exit.

Commands:
migrations Runs migration operations.
run Runs a development server.
shell Runs a shell in the app context.
--------------------------------------------------------------------------------------------------------------------------------

running "weppy -a bloggy.py setup" or "weppy --app bloggy.py setup" looks like this:

Usage: weppy [OPTIONS] COMMAND [ARGS]...

Error: No such command "setup".

--------------------------------------------------------------------------------------------------------------------------------

running "weppy -a bloggy.py run" the output looks like this:

Traceback (most recent call last):
  File "/var/www/virts/tjtimer/bin/weppy", line 9, in <module>
    load_entry_point('weppy==0.6', 'console_scripts', 'weppy')()
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/weppy/cli.py", line 358, in main
    cli.main(args=args, prog_name=name)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/weppy/cli.py", line 209, in main
    return click.Group.main(self, *args, **kwargs)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/weppy/cli.py", line 222, in run_command
    app = info.load_app()
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/weppy/cli.py", line 136, in load_app
    a = locate_app(self.app_import_path)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/weppy/cli.py", line 98, in locate_app
    module, mod, app_obj = get_app_module(app_id)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/weppy/cli.py", line 91, in get_app_module
    __import__(module)
  File "/var/www/tjs_weppy_app/bloggy.py", line 60, in <module>
    auth = Auth(app, db, usermodel=User)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/weppy/tools/auth/engine.py", line 107, in __init__
    self.define_models()
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/weppy/tools/auth/engine.py", line 277, in define_models
    models.event
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/weppy/dal/base.py", line 269, in define_models
    obj.tablename, *obj.fields, **args
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/pydal/base.py", line 834, in define_table
    table = self.lazy_define_table(tablename,*fields,**args)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/pydal/base.py", line 873, in lazy_define_table
    polymodel=polymodel)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/pydal/adapters/base.py", line 482, in create_table
    self.create_sequence_and_triggers(query, table)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/pydal/adapters/postgres.py", line 94, in create_sequence_and_triggers
    self.execute(query)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/pydal/adapters/postgres.py", line 360, in execute
    return BaseAdapter.execute(self, *a, **b)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/pydal/adapters/base.py", line 1385, in execute
    return self.log_execute(*a, **b)
  File "/var/www/virts/tjtimer/lib/python3.5/site-packages/pydal/adapters/base.py", line 1379, in log_execute
    ret = self.get_cursor().execute(command, *a[1:], **b)
psycopg2.ProgrammingError: syntax error at or near "user"
LINE 5:     user INTEGER REFERENCES users (id) ON DELETE CASCADE  ,
            ^
--------------------------------------------------------------------------------------------------------------------------------
thanks in advance
Tim

**Comment by gi0baro** [comment] 2016-01-29 14:30
Hi @tjtimer,
seems that the problem is related to the reserved name for the *user* column with PostgreSQL.
I'm gonna investigate this but seems related to the pydal library that is not escaping column names on table creation.

Will update you soon.

**Comment by gi0baro** [comment] 2016-01-30 10:17
Hi @tjtimer, this is due to pydal default not quoting the column names of the tables. I will propose an update in order to change this behavior.

In the meantime, the temporary fix is to initialize the `DAL` instance with the `entity_quoting` parameter set to `True`:

```python
db = DAL(app, entity_quoting=True)
```

I'm also going to change the title of the issue to better identify the bug.

**Comment by gi0baro** [comment] 2016-06-06 21:32
This is fixed on the current master and will be released with 0.7

**Closed by gi0baro** 2016-06-06 21:32 UTC
Labels: bug
