### ISSUE TITLE
Please create full examples

### ISSUE THREAD

**Issue by ramstein74** [gi0baro/weppy#51] opened 2015-11-03 11:04 UTC
Hello, your sample code in docs do not work out of the box.
Its not clear that the full code should be written.
For example i´m trying to understand how to create a form

your docs says

form weppy import Field, Form
from weppy.validators import inSet

@app.expose('/form')
def a():
    simple_form = Form({
        'name': Field(),
        'number': Field('int'),
        'type': Field(
            validation={'in': ['type1', 'type2']}
        )
    })
    if simple_form.accepted:
        #do something
    return dict(form=simple_form)

but this is not enough to create a valid form code

i´m not sure but i thing i need to add 
from weppy import App
app = App(__name__)

and 
if __name__ == "__main__":
    app.run()

Please be more patient with dummies like me and most of the people that follows you.

Regards

**Comment by gi0baro** [comment] 2015-11-05 09:04
I'm closing this since it's a duplicate of #52

**Closed by gi0baro** 2015-11-05 09:04 UTC
