### ISSUE TITLE
Possible bug in stream_dbfile

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy#187] opened 2017-03-15 17:14 UTC
Hi @gi0baro,
I do not know where the problem may be. I will try to put the maximum information about what is happening.

Given a model with an upload field, an image in my case.

In development mode works fine. I upload the image and I can show it on some page, but in production (nginx + gunicorn) the following happens:

- The image is uploaded well to the server
- The image fails to display on the page

I did this test:

Create a tunnel to the server to access port 8000 and start the development server from weppy.

[develop]
1) I uploaded the image and I could see it without problems

[nginx]
2) Try to view image uploaded in (1) and fail.
3) I uploaded another image but could not see it

[develop]
4) I can see the image uploaded in (3)

The download function is this:

```
@app.route("/download/<str:filename>")
def download(filename):
    stream_dbfile(db, filename)

```
If I copy the url of the image and paste it in another tab, sometimes it gives:
"Internal Server Error" and other times malformed image

There is no error in the nginx log.

If you need any further proof, please let me know.

Jose

**Comment by gi0baro** [comment] 2017-03-15 18:30
@josejachuf in production you should have exceptions logged into *logs/production.log* inside your application package. Can you check it out and see if you have anything useful there?

**Comment by josejachuf** [comment] 2017-03-15 18:50
@gi0baro 

Nothing, just this message:
[2017-03-15 15:47:47,604] WARNING in ext: No mailer seems to be configured. The auth features requiring mailer won't work.

**Comment by josejachuf** [comment] 2017-03-15 19:23
I bring something else.
Configuring the same environment (nginx + gunicorn) locally, (with w0.85 and w1.0) but with python27 another application that I have works well. I'm going to test with python3 that the one I have on the server.

The problem is likely to come from elsewhere.

**Comment by josejachuf** [comment] 2017-03-15 19:55
I do not know if I have any problems in the configuration, but it gives me problems with gunicorn with python3, with python2 everything works fine. I'll look for that side

**Comment by josejachuf** [comment] 2017-03-15 21:28
The problem is definitely in gunicorn with python3. I switched to uwsgi and it works fine.
I'll see that it can be changed

**Comment by josejachuf** [comment] 2017-03-24 02:46
@gi0baro 

Viewing the gunicorn log, this [1] is the same problem that occurs with python3 and gunicorn.

In the end the author writes: _**closing an issue as this bug happen outside of gunicorn.**_

Jose


[1] https://github.com/benoitc/gunicorn/issues/1214

**Comment by gi0baro** [comment] 2017-03-27 21:40
@josejachuf I'm reopening this 'till I verify what happens with gunicorn and python3.

**Comment by josejachuf** [comment] 2017-03-29 15:44
@gi0baro 

with python36 and gunicorn, downloading in this way, works fine

    ```
buffer_stream = io.BytesIO()
    template_doc.save(buffer_stream)
    response.headers['Content-Type']='application/docx'
    response.headers['Content-Disposition'] = 'attachment; filename=o_%d.docx'%obj.numero

    return buffer_stream.getvalue()
```
Jose

**Comment by josejachuf** [comment] 2017-03-29 16:59
Also gives problems with these files: __weppy__

> 
> [2017-03-29 13:28:09 -0300] [12852] [ERROR] Error handling request /__weppy__/jquery.min.js
> Traceback (most recent call last):
>   File "/usr/home/www/venv36/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
>     self.handle_request(listener, req, client, addr)
>   File "/usr/home/www/venv36/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
>     resp.write_file(respiter)
>   File "/usr/home/www/venv36/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 411, in write_file
>     if not self.sendfile(respiter):
>   File "/usr/home/www/venv36/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 390, in sendfile
>     self.send_headers()
>   File "/usr/home/www/venv36/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 337, in send_headers
>     util.write(self.sock, util.to_bytestring(header_str, "ascii"))
>   File "/usr/home/www/venv36/lib/python3.6/site-packages/gunicorn/util.py", line 509, in to_bytestring
>     return value.encode(encoding)
> UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 153: ordinal not in range(128)

**Comment by gi0baro** [comment] 2017-07-13 18:12
@josejachuf I tried to reproduce this today but on python 3.5.2 and gunicorn 19.7.1 the url `/__weppy__/jquery.min.js` is served correctly.

Run with `gunicorn -w 4 bloggy:app` on bloggy example.
Will try also on `stream_dbfile` but the streamer seems ok.

**Comment by gi0baro** [comment] 2017-07-17 09:01
@josejachuf I've tested with `stream_dbfile` too and I can't reproduce the error. I'm closing this.

**Closed by gi0baro** 2017-07-17 09:01 UTC
Labels: bug

**Comment by josejachuf** [comment] 2017-07-17 14:43
Hi @gi0baro 

I just tried, setting up the same environment and everything works fine. Or changed weppy (or dependencies), or changed gunicorn (or dependencies) or changed nginx.

I tried getting down to weppy 1.0.2 and it still works fine. Also go down to gunicorn 19.7.0 which is the one used when I published this problem

I do not know what it might have been, maybe some layer of dependencies below.

Jose

**Comment by josejachuf** [comment] 2017-09-23 21:55
@gi0baro , the same problem continues to occur.
This is the output of gunicorn:

> [2017-09-23 18:48:37 -0300] [69927] [ERROR] Error handling request /__weppy__/helpers.js
> Traceback (most recent call last):
>   File "/usr/home/www/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
>     self.handle_request(listener, req, client, addr)
>   File "/usr/home/www/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
>     resp.write_file(respiter)
>   File "/usr/home/www/venv/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 411, in write_file
>     if not self.sendfile(respiter):
>   File "/usr/home/www/venv/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 390, in sendfile
>     self.send_headers()
>   File "/usr/home/www/venv/lib/python3.6/site-packages/gunicorn/http/wsgi.py", line 337, in send_headers
>     util.write(self.sock, util.to_bytestring(header_str, "ascii"))
>   File "/usr/home/www/venv/lib/python3.6/site-packages/gunicorn/util.py", line 509, in to_bytestring
>     return value.encode(encoding)
> UnicodeEncodeError: 'ascii' codec can't encode character '\xe1' in position 152: ordinal not in range(128)

when is called: 

> my_domain/__weppy__/helpers.js (weppy between double underscore)

**Comment by josejachuf** [comment] 2017-09-24 00:30
@gi0baro I already found because the error and the solution to this. It is related to this [1]. To solve the problem in the templates I use the following in the __ini__.py of the application:
```
import locale
locale.setlocale(locale.LC_ALL,'es_ES.UTF-8')
```
The previous lines correct the templates, but apparently with gunicorn gives me the mentioned problem.
Removing these lines solves everything and is more, in production is not given the error [1] in the templates. It should be related to the behavior you mentioned to me in [2], about how the behavior of the templates in development and in production differs.

Jose

[1] https://groups.google.com/forum/#!topic/weppy-talk/GjVGJ3O3p80
[2] https://groups.google.com/forum/#!topic/weppy-talk/jXbEmEdmcwc

**Comment by josejachuf** [comment] 2017-09-24 00:54
![development](https://user-images.githubusercontent.com/5981345/30778337-c588a812-a0a9-11e7-9534-1ed90ccb79b6.jpg)
![production](https://user-images.githubusercontent.com/5981345/30778338-c58f7f70-a0a9-11e7-96f4-aadcdb97009b.jpg)

**Comment by gi0baro** [comment] 2017-09-25 09:33
@josejachuf this sounds really strange to me. The templating system shouldn't change the way it handles unicode/utf-8 from when it has reloader or not.
Are you using Python 3? The templating system will use unicode both on Python 2 and 3 versions. I've never faced these errors with italian language. The fact is: if you handle non-utf8 characters you should use python in templates, since the system should handle the rest.

**Comment by josejachuf** [comment] 2017-09-25 10:50
@gi0baro Yes, I am using python3. This has happened since I started with weppy, version 0.6 or 0.7 through 1.1.1.
This is my locale:

> % locale
> LANG=es_AR.ISO8859-1
> LC_CTYPE="es_AR.ISO8859-1"
> LC_COLLATE="es_AR.ISO8859-1"
> LC_TIME="es_AR.ISO8859-1"
> LC_NUMERIC="es_AR.ISO8859-1"
> LC_MONETARY="es_AR.ISO8859-1"
> LC_MESSAGES="es_AR.ISO8859-1"
> LC_ALL=
> 
Jose

**Comment by josejachuf** [comment] 2017-09-25 11:04
Changing LANG works fine:

`% setenv LANG es_AR.UTF-8`

You can show the output of your locale

Jose

**Comment by gi0baro** [comment] 2017-09-26 10:19
@josejachuf here is my locale:

```
(weppytestpy3) ➜  bloggy git:(master) ✗ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
